'use strict';

//require needs to be installed via node or included in the "browser" defs in package.json for browserify to pick up the lib
var angular = require('angular');
var uir = require('angular-ui-router');
var uibs = require('angular-ui-bootstrap');

// Include a comment about why this seemingly unused module exists
//this is used to add the view html templates that are generated by gulp on build
angular.module('templatescache', []);

// Main app definition
var mod = angular.module('app', [uir, uibs, 'templatescache']);

angular.module('app')
    .run(
    ['$rootScope', '$state', '$stateParams', '$location', function ($rootScope, $state, $stateParams, $location) {

        // It's very handy to add references to $state and $stateParams to the $rootScope
        // so that you can access them from any scope within your applications.For example,
        // <li ng-class="{ active: $state.includes('contacts.list') }"> will set the <li>
        // to active whenever 'contacts.list' or one of its decendents is active.
        $rootScope.$location = $location;
        $rootScope.$state = $state;
        $rootScope.$stateParams = $stateParams;
    }]
)
    .config(['$stateProvider', '$urlRouterProvider', function ($stateProvider, $urlRouterProvider) {
        // Redirects and Otherwise //
        // Use $urlRouterProvider to configure any redirects (when) and invalid urls (otherwise).
        $urlRouterProvider
            .otherwise('/main/sub');

        // State Configurations //
        // Use $stateProvider to configure your states.
        $stateProvider

            .state('main', {
                abstract: true,
                templateUrl: 'views/main/main.html',
                url: '/main'
            })
            .state('main.sub', {
                url: '/sub',
                views: {
                    'view1': {
                        templateUrl: 'views/main/view1.html'
                    },
                    'view2': {
                        templateUrl: 'views/main/view2.html',
                        controller: 'mainCtrl'
                    }
                }
            })

    }]);


//
// include all the necessary js files ( controllers, services, directors, filters... etc )
//
require('./views/main/index.js')(mod);

